// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anicoll/winet-integration/internal/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// NewDataPublisher creates a new instance of DataPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataPublisher {
	mock := &DataPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DataPublisher is an autogenerated mock type for the DataPublisher type
type DataPublisher struct {
	mock.Mock
}

type DataPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *DataPublisher) EXPECT() *DataPublisher_Expecter {
	return &DataPublisher_Expecter{mock: &_m.Mock}
}

// PublishData provides a mock function for the type DataPublisher
func (_mock *DataPublisher) PublishData(ctx context.Context, devices map[model.Device][]model.DeviceStatus) error {
	ret := _mock.Called(ctx, devices)

	if len(ret) == 0 {
		panic("no return value specified for PublishData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[model.Device][]model.DeviceStatus) error); ok {
		r0 = returnFunc(ctx, devices)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataPublisher_PublishData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishData'
type DataPublisher_PublishData_Call struct {
	*mock.Call
}

// PublishData is a helper method to define mock.On call
//   - ctx context.Context
//   - devices map[model.Device][]model.DeviceStatus
func (_e *DataPublisher_Expecter) PublishData(ctx interface{}, devices interface{}) *DataPublisher_PublishData_Call {
	return &DataPublisher_PublishData_Call{Call: _e.mock.On("PublishData", ctx, devices)}
}

func (_c *DataPublisher_PublishData_Call) Run(run func(ctx context.Context, devices map[model.Device][]model.DeviceStatus)) *DataPublisher_PublishData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[model.Device][]model.DeviceStatus
		if args[1] != nil {
			arg1 = args[1].(map[model.Device][]model.DeviceStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataPublisher_PublishData_Call) Return(err error) *DataPublisher_PublishData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataPublisher_PublishData_Call) RunAndReturn(run func(ctx context.Context, devices map[model.Device][]model.DeviceStatus) error) *DataPublisher_PublishData_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterDevice provides a mock function for the type DataPublisher
func (_mock *DataPublisher) RegisterDevice(ctx context.Context, device *model.Device) error {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Device) error); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataPublisher_RegisterDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDevice'
type DataPublisher_RegisterDevice_Call struct {
	*mock.Call
}

// RegisterDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - device *model.Device
func (_e *DataPublisher_Expecter) RegisterDevice(ctx interface{}, device interface{}) *DataPublisher_RegisterDevice_Call {
	return &DataPublisher_RegisterDevice_Call{Call: _e.mock.On("RegisterDevice", ctx, device)}
}

func (_c *DataPublisher_RegisterDevice_Call) Run(run func(ctx context.Context, device *model.Device)) *DataPublisher_RegisterDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Device
		if args[1] != nil {
			arg1 = args[1].(*model.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataPublisher_RegisterDevice_Call) Return(err error) *DataPublisher_RegisterDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataPublisher_RegisterDevice_Call) RunAndReturn(run func(ctx context.Context, device *model.Device) error) *DataPublisher_RegisterDevice_Call {
	_c.Call.Return(run)
	return _c
}
