// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anicoll/winet-integration/internal/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

type Publisher_Expecter struct {
	mock *mock.Mock
}

func (_m *Publisher) EXPECT() *Publisher_Expecter {
	return &Publisher_Expecter{mock: &_m.Mock}
}

// RegisterDevice provides a mock function for the type Publisher
func (_mock *Publisher) RegisterDevice(ctx context.Context, device *model.Device) error {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Device) error); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Publisher_RegisterDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDevice'
type Publisher_RegisterDevice_Call struct {
	*mock.Call
}

// RegisterDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - device *model.Device
func (_e *Publisher_Expecter) RegisterDevice(ctx interface{}, device interface{}) *Publisher_RegisterDevice_Call {
	return &Publisher_RegisterDevice_Call{Call: _e.mock.On("RegisterDevice", ctx, device)}
}

func (_c *Publisher_RegisterDevice_Call) Run(run func(ctx context.Context, device *model.Device)) *Publisher_RegisterDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Device
		if args[1] != nil {
			arg1 = args[1].(*model.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Publisher_RegisterDevice_Call) Return(err error) *Publisher_RegisterDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Publisher_RegisterDevice_Call) RunAndReturn(run func(ctx context.Context, device *model.Device) error) *Publisher_RegisterDevice_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type Publisher
func (_mock *Publisher) Write(ctx context.Context, data []map[string]any) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []map[string]any) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Publisher_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type Publisher_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - data []map[string]any
func (_e *Publisher_Expecter) Write(ctx interface{}, data interface{}) *Publisher_Write_Call {
	return &Publisher_Write_Call{Call: _e.mock.On("Write", ctx, data)}
}

func (_c *Publisher_Write_Call) Run(run func(ctx context.Context, data []map[string]any)) *Publisher_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []map[string]any
		if args[1] != nil {
			arg1 = args[1].([]map[string]any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Publisher_Write_Call) Return(err error) *Publisher_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Publisher_Write_Call) RunAndReturn(run func(ctx context.Context, data []map[string]any) error) *Publisher_Write_Call {
	_c.Call.Return(run)
	return _c
}
