// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anicoll/winet-integration/internal/pkg/database/db"
	mock "github.com/stretchr/testify/mock"
)

// NewAmberUsageWriter creates a new instance of AmberUsageWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAmberUsageWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *AmberUsageWriter {
	mock := &AmberUsageWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AmberUsageWriter is an autogenerated mock type for the AmberUsageWriter type
type AmberUsageWriter struct {
	mock.Mock
}

type AmberUsageWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *AmberUsageWriter) EXPECT() *AmberUsageWriter_Expecter {
	return &AmberUsageWriter_Expecter{mock: &_m.Mock}
}

// WriteAmberUsage provides a mock function for the type AmberUsageWriter
func (_mock *AmberUsageWriter) WriteAmberUsage(ctx context.Context, usage []db.Amberusage) error {
	ret := _mock.Called(ctx, usage)

	if len(ret) == 0 {
		panic("no return value specified for WriteAmberUsage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.Amberusage) error); ok {
		r0 = returnFunc(ctx, usage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AmberUsageWriter_WriteAmberUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAmberUsage'
type AmberUsageWriter_WriteAmberUsage_Call struct {
	*mock.Call
}

// WriteAmberUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - usage []db.Amberusage
func (_e *AmberUsageWriter_Expecter) WriteAmberUsage(ctx interface{}, usage interface{}) *AmberUsageWriter_WriteAmberUsage_Call {
	return &AmberUsageWriter_WriteAmberUsage_Call{Call: _e.mock.On("WriteAmberUsage", ctx, usage)}
}

func (_c *AmberUsageWriter_WriteAmberUsage_Call) Run(run func(ctx context.Context, usage []db.Amberusage)) *AmberUsageWriter_WriteAmberUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []db.Amberusage
		if args[1] != nil {
			arg1 = args[1].([]db.Amberusage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AmberUsageWriter_WriteAmberUsage_Call) Return(err error) *AmberUsageWriter_WriteAmberUsage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AmberUsageWriter_WriteAmberUsage_Call) RunAndReturn(run func(ctx context.Context, usage []db.Amberusage) error) *AmberUsageWriter_WriteAmberUsage_Call {
	_c.Call.Return(run)
	return _c
}
