// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anicoll/winet-integration/internal/pkg/database/db"
	mock "github.com/stretchr/testify/mock"
)

// NewAmberPricesWriter creates a new instance of AmberPricesWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAmberPricesWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *AmberPricesWriter {
	mock := &AmberPricesWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AmberPricesWriter is an autogenerated mock type for the AmberPricesWriter type
type AmberPricesWriter struct {
	mock.Mock
}

type AmberPricesWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *AmberPricesWriter) EXPECT() *AmberPricesWriter_Expecter {
	return &AmberPricesWriter_Expecter{mock: &_m.Mock}
}

// WriteAmberPrices provides a mock function for the type AmberPricesWriter
func (_mock *AmberPricesWriter) WriteAmberPrices(ctx context.Context, prices []db.Amberprice) error {
	ret := _mock.Called(ctx, prices)

	if len(ret) == 0 {
		panic("no return value specified for WriteAmberPrices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.Amberprice) error); ok {
		r0 = returnFunc(ctx, prices)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AmberPricesWriter_WriteAmberPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAmberPrices'
type AmberPricesWriter_WriteAmberPrices_Call struct {
	*mock.Call
}

// WriteAmberPrices is a helper method to define mock.On call
//   - ctx context.Context
//   - prices []db.Amberprice
func (_e *AmberPricesWriter_Expecter) WriteAmberPrices(ctx interface{}, prices interface{}) *AmberPricesWriter_WriteAmberPrices_Call {
	return &AmberPricesWriter_WriteAmberPrices_Call{Call: _e.mock.On("WriteAmberPrices", ctx, prices)}
}

func (_c *AmberPricesWriter_WriteAmberPrices_Call) Run(run func(ctx context.Context, prices []db.Amberprice)) *AmberPricesWriter_WriteAmberPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []db.Amberprice
		if args[1] != nil {
			arg1 = args[1].([]db.Amberprice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AmberPricesWriter_WriteAmberPrices_Call) Return(err error) *AmberPricesWriter_WriteAmberPrices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AmberPricesWriter_WriteAmberPrices_Call) RunAndReturn(run func(ctx context.Context, prices []db.Amberprice) error) *AmberPricesWriter_WriteAmberPrices_Call {
	_c.Call.Return(run)
	return _c
}
