// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anicoll/winet-integration/internal/pkg/database/db"
	"github.com/oapi-codegen/runtime/types"
	mock "github.com/stretchr/testify/mock"
)

// NewAmberUsageFetcher creates a new instance of AmberUsageFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAmberUsageFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *AmberUsageFetcher {
	mock := &AmberUsageFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AmberUsageFetcher is an autogenerated mock type for the AmberUsageFetcher type
type AmberUsageFetcher struct {
	mock.Mock
}

type AmberUsageFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *AmberUsageFetcher) EXPECT() *AmberUsageFetcher_Expecter {
	return &AmberUsageFetcher_Expecter{mock: &_m.Mock}
}

// GetUsage provides a mock function for the type AmberUsageFetcher
func (_mock *AmberUsageFetcher) GetUsage(ctx context.Context, siteID string, startDate types.Date, endDate types.Date) ([]db.Amberusage, error) {
	ret := _mock.Called(ctx, siteID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetUsage")
	}

	var r0 []db.Amberusage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Date, types.Date) ([]db.Amberusage, error)); ok {
		return returnFunc(ctx, siteID, startDate, endDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Date, types.Date) []db.Amberusage); ok {
		r0 = returnFunc(ctx, siteID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Amberusage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Date, types.Date) error); ok {
		r1 = returnFunc(ctx, siteID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AmberUsageFetcher_GetUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsage'
type AmberUsageFetcher_GetUsage_Call struct {
	*mock.Call
}

// GetUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - siteID string
//   - startDate types.Date
//   - endDate types.Date
func (_e *AmberUsageFetcher_Expecter) GetUsage(ctx interface{}, siteID interface{}, startDate interface{}, endDate interface{}) *AmberUsageFetcher_GetUsage_Call {
	return &AmberUsageFetcher_GetUsage_Call{Call: _e.mock.On("GetUsage", ctx, siteID, startDate, endDate)}
}

func (_c *AmberUsageFetcher_GetUsage_Call) Run(run func(ctx context.Context, siteID string, startDate types.Date, endDate types.Date)) *AmberUsageFetcher_GetUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Date
		if args[2] != nil {
			arg2 = args[2].(types.Date)
		}
		var arg3 types.Date
		if args[3] != nil {
			arg3 = args[3].(types.Date)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AmberUsageFetcher_GetUsage_Call) Return(amberusages []db.Amberusage, err error) *AmberUsageFetcher_GetUsage_Call {
	_c.Call.Return(amberusages, err)
	return _c
}

func (_c *AmberUsageFetcher_GetUsage_Call) RunAndReturn(run func(ctx context.Context, siteID string, startDate types.Date, endDate types.Date) ([]db.Amberusage, error)) *AmberUsageFetcher_GetUsage_Call {
	_c.Call.Return(run)
	return _c
}
