// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anicoll/winet-integration/internal/pkg/winet"
	mock "github.com/stretchr/testify/mock"
)

// NewWinetConnector creates a new instance of WinetConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWinetConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *WinetConnector {
	mock := &WinetConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WinetConnector is an autogenerated mock type for the WinetConnector type
type WinetConnector struct {
	mock.Mock
}

type WinetConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *WinetConnector) EXPECT() *WinetConnector_Expecter {
	return &WinetConnector_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type WinetConnector
func (_mock *WinetConnector) Connect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WinetConnector_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type WinetConnector_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WinetConnector_Expecter) Connect(ctx interface{}) *WinetConnector_Connect_Call {
	return &WinetConnector_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *WinetConnector_Connect_Call) Run(run func(ctx context.Context)) *WinetConnector_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WinetConnector_Connect_Call) Return(err error) *WinetConnector_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WinetConnector_Connect_Call) RunAndReturn(run func(ctx context.Context) error) *WinetConnector_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function for the type WinetConnector
func (_mock *WinetConnector) Events() <-chan winet.SessionEvent {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 <-chan winet.SessionEvent
	if returnFunc, ok := ret.Get(0).(func() <-chan winet.SessionEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan winet.SessionEvent)
		}
	}
	return r0
}

// WinetConnector_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type WinetConnector_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
func (_e *WinetConnector_Expecter) Events() *WinetConnector_Events_Call {
	return &WinetConnector_Events_Call{Call: _e.mock.On("Events")}
}

func (_c *WinetConnector_Events_Call) Run(run func()) *WinetConnector_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WinetConnector_Events_Call) Return(sessionEventCh <-chan winet.SessionEvent) *WinetConnector_Events_Call {
	_c.Call.Return(sessionEventCh)
	return _c
}

func (_c *WinetConnector_Events_Call) RunAndReturn(run func() <-chan winet.SessionEvent) *WinetConnector_Events_Call {
	_c.Call.Return(run)
	return _c
}
