// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: amber_usage.sql

package db

import (
	"context"
	"time"
)

const getAmberUsage = `-- name: GetAmberUsage :many
SELECT id, per_kwh, spot_per_kwh, start_time, end_time, duration, channel_type, channel_identifier, kwh, quality, cost, created_at, updated_at
FROM AmberUsage
WHERE start_time BETWEEN $1 AND $2
ORDER BY start_time DESC
`

type GetAmberUsageParams struct {
	StartTime   time.Time `json:"start_time"`
	StartTime_2 time.Time `json:"start_time_2"`
}

func (q *Queries) GetAmberUsage(ctx context.Context, arg GetAmberUsageParams) ([]Amberusage, error) {
	rows, err := q.db.Query(ctx, getAmberUsage, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amberusage
	for rows.Next() {
		var i Amberusage
		if err := rows.Scan(
			&i.ID,
			&i.PerKwh,
			&i.SpotPerKwh,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
			&i.ChannelType,
			&i.ChannelIdentifier,
			&i.Kwh,
			&i.Quality,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAmberUsage = `-- name: UpsertAmberUsage :exec
INSERT INTO AmberUsage (per_kwh, spot_per_kwh, start_time, end_time, duration, channel_type, channel_identifier, kwh, quality, cost)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (start_time, channel_identifier) DO UPDATE
SET per_kwh      = EXCLUDED.per_kwh,
    spot_per_kwh = EXCLUDED.spot_per_kwh,
    duration     = EXCLUDED.duration,
    kwh          = EXCLUDED.kwh,
    quality      = EXCLUDED.quality,
    cost         = EXCLUDED.cost,
    updated_at   = NOW()
`

type UpsertAmberUsageParams struct {
	PerKwh            float64   `json:"per_kwh"`
	SpotPerKwh        float64   `json:"spot_per_kwh"`
	StartTime         time.Time `json:"start_time"`
	EndTime           time.Time `json:"end_time"`
	Duration          int       `json:"duration"`
	ChannelType       string    `json:"channel_type"`
	ChannelIdentifier string    `json:"channel_identifier"`
	Kwh               float64   `json:"kwh"`
	Quality           string    `json:"quality"`
	Cost              float64   `json:"cost"`
}

func (q *Queries) UpsertAmberUsage(ctx context.Context, arg UpsertAmberUsageParams) error {
	_, err := q.db.Exec(ctx, upsertAmberUsage,
		arg.PerKwh,
		arg.SpotPerKwh,
		arg.StartTime,
		arg.EndTime,
		arg.Duration,
		arg.ChannelType,
		arg.ChannelIdentifier,
		arg.Kwh,
		arg.Quality,
		arg.Cost,
	)
	return err
}
