// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: amber_prices.sql

package db

import (
	"context"
	"time"
)

const getAmberPrices = `-- name: GetAmberPrices :many
SELECT id, per_kwh, spot_per_kwh, start_time, end_time, duration, forecast, channel_type, created_at, updated_at
FROM AmberPrice
WHERE start_time BETWEEN $1 AND $2
ORDER BY start_time DESC
`

type GetAmberPricesParams struct {
	StartTime   time.Time `json:"start_time"`
	StartTime_2 time.Time `json:"start_time_2"`
}

func (q *Queries) GetAmberPrices(ctx context.Context, arg GetAmberPricesParams) ([]Amberprice, error) {
	rows, err := q.db.Query(ctx, getAmberPrices, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amberprice
	for rows.Next() {
		var i Amberprice
		if err := rows.Scan(
			&i.ID,
			&i.PerKwh,
			&i.SpotPerKwh,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
			&i.Forecast,
			&i.ChannelType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAmberPrice = `-- name: UpsertAmberPrice :exec
INSERT INTO AmberPrice (per_kwh, spot_per_kwh, start_time, end_time, duration, forecast, channel_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (start_time, channel_type) DO UPDATE
SET per_kwh      = EXCLUDED.per_kwh,
    spot_per_kwh = EXCLUDED.spot_per_kwh,
    duration     = EXCLUDED.duration,
    forecast     = EXCLUDED.forecast,
    updated_at   = NOW()
`

type UpsertAmberPriceParams struct {
	PerKwh      float64   `json:"per_kwh"`
	SpotPerKwh  float64   `json:"spot_per_kwh"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	Duration    int       `json:"duration"`
	Forecast    bool      `json:"forecast"`
	ChannelType string    `json:"channel_type"`
}

func (q *Queries) UpsertAmberPrice(ctx context.Context, arg UpsertAmberPriceParams) error {
	_, err := q.db.Exec(ctx, upsertAmberPrice,
		arg.PerKwh,
		arg.SpotPerKwh,
		arg.StartTime,
		arg.EndTime,
		arg.Duration,
		arg.Forecast,
		arg.ChannelType,
	)
	return err
}
