// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO Device (id, model, serial_number)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type UpsertDeviceParams struct {
	ID           string      `json:"id"`
	Model        pgtype.Text `json:"model"`
	SerialNumber pgtype.Text `json:"serial_number"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice, arg.ID, arg.Model, arg.SerialNumber)
	return err
}
