// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Amberprice struct {
	ID          int                `json:"id"`
	PerKwh      float64            `json:"per_kwh"`
	SpotPerKwh  float64            `json:"spot_per_kwh"`
	StartTime   time.Time          `json:"start_time"`
	EndTime     time.Time          `json:"end_time"`
	Duration    int                `json:"duration"`
	Forecast    bool               `json:"forecast"`
	ChannelType string             `json:"channel_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Device struct {
	ID           string             `json:"id"`
	Model        pgtype.Text        `json:"model"`
	SerialNumber pgtype.Text        `json:"serial_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Inverter struct {
	ID            string             `json:"id"`
	State         string             `json:"state"`
	BatteryState  string             `json:"battery_state"`
	ChargeRate    float64            `json:"charge_rate"`
	FeedinEnabled bool               `json:"feedin_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Property struct {
	ID                int       `json:"id"`
	TimeStamp         time.Time `json:"time_stamp"`
	UnitOfMeasurement string    `json:"unit_of_measurement"`
	Value             string    `json:"value"`
	Identifier        string    `json:"identifier"`
	Slug              string    `json:"slug"`
}
