// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: properties.sql

package db

import (
	"context"
	"time"
)

const cleanupProperties = `-- name: CleanupProperties :exec
DELETE FROM Property WHERE time_stamp < $1
`

func (q *Queries) CleanupProperties(ctx context.Context, timeStamp time.Time) error {
	_, err := q.db.Exec(ctx, cleanupProperties, timeStamp)
	return err
}

const getLatestProperties = `-- name: GetLatestProperties :many
SELECT DISTINCT ON (identifier, slug)
    id, time_stamp, unit_of_measurement, value, identifier, slug
FROM Property
WHERE time_stamp > NOW() - INTERVAL '1 day'
ORDER BY identifier, slug, time_stamp DESC
`

func (q *Queries) GetLatestProperties(ctx context.Context) ([]Property, error) {
	rows, err := q.db.Query(ctx, getLatestProperties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.TimeStamp,
			&i.UnitOfMeasurement,
			&i.Value,
			&i.Identifier,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProperties = `-- name: GetProperties :many
SELECT id, time_stamp, unit_of_measurement, value, identifier, slug
FROM Property
WHERE identifier = $1 AND slug = $2 AND time_stamp BETWEEN $3 AND $4
ORDER BY time_stamp DESC
`

type GetPropertiesParams struct {
	Identifier  string    `json:"identifier"`
	Slug        string    `json:"slug"`
	TimeStamp   time.Time `json:"time_stamp"`
	TimeStamp_2 time.Time `json:"time_stamp_2"`
}

func (q *Queries) GetProperties(ctx context.Context, arg GetPropertiesParams) ([]Property, error) {
	rows, err := q.db.Query(ctx, getProperties,
		arg.Identifier,
		arg.Slug,
		arg.TimeStamp,
		arg.TimeStamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.TimeStamp,
			&i.UnitOfMeasurement,
			&i.Value,
			&i.Identifier,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProperty = `-- name: InsertProperty :one
INSERT INTO Property (time_stamp, unit_of_measurement, value, identifier, slug)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, time_stamp, unit_of_measurement, value, identifier, slug
`

type InsertPropertyParams struct {
	TimeStamp         time.Time `json:"time_stamp"`
	UnitOfMeasurement string    `json:"unit_of_measurement"`
	Value             string    `json:"value"`
	Identifier        string    `json:"identifier"`
	Slug              string    `json:"slug"`
}

func (q *Queries) InsertProperty(ctx context.Context, arg InsertPropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, insertProperty,
		arg.TimeStamp,
		arg.UnitOfMeasurement,
		arg.Value,
		arg.Identifier,
		arg.Slug,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.TimeStamp,
		&i.UnitOfMeasurement,
		&i.Value,
		&i.Identifier,
		&i.Slug,
	)
	return i, err
}
