log-level: warn
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
pkgname: mocks
template: testify
packages:
  github.com/anicoll/winet-integration/cmd:
    config:
      dir: "mocks/cmd"
    interfaces:
      AmberUsageFetcher:
      AmberUsageWriter:
      WinetConnector:
  github.com/anicoll/winet-integration/pkg/sockets:
    config:
      dir: "mocks/sockets"
    interfaces:
      Connection:
  github.com/anicoll/winet-integration/internal/pkg/publisher:
    config:
      dir: "mocks/publisher"
    interfaces:
      DataPublisher:
  github.com/anicoll/winet-integration/internal/pkg/logic:
    config:
      dir: "mocks/logic"
    interfaces:
      WinetCommands:
      Database:
  github.com/anicoll/winet-integration/internal/pkg/server:
    config:
      dir: "mocks/server"
    interfaces:
      WinetService:
      Database:
  github.com/anicoll/winet-integration/internal/pkg/auth:
    config:
      dir: "mocks/auth"
    interfaces:
      UserStore:
      TokenStore:
