//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ChangeBatteryStatePayloadState.
const (
	Charge          ChangeBatteryStatePayloadState = "charge"
	Discharge       ChangeBatteryStatePayloadState = "discharge"
	SelfConsumption ChangeBatteryStatePayloadState = "self_consumption"
	Stop            ChangeBatteryStatePayloadState = "stop"
)

// Valid indicates whether the value is a known member of the ChangeBatteryStatePayloadState enum.
func (e ChangeBatteryStatePayloadState) Valid() bool {
	switch e {
	case Charge:
		return true
	case Discharge:
		return true
	case SelfConsumption:
		return true
	case Stop:
		return true
	default:
		return false
	}
}

// Defines values for ChangeInverterStatePayloadState.
const (
	Off ChangeInverterStatePayloadState = "off"
	On  ChangeInverterStatePayloadState = "on"
)

// Valid indicates whether the value is a known member of the ChangeInverterStatePayloadState enum.
func (e ChangeInverterStatePayloadState) Valid() bool {
	switch e {
	case Off:
		return true
	case On:
		return true
	default:
		return false
	}
}

// AmberPrice defines model for AmberPrice.
type AmberPrice struct {
	// ChannelType indicates if the price is feedin or general.
	ChannelType string    `json:"channelType"`
	CreatedAt   time.Time `json:"createdAt"`

	// Duration duration in minutes
	Duration int       `json:"duration"`
	EndTime  time.Time `json:"endTime"`

	// Forecast indicates if the price is a forecast price or not.
	Forecast   bool      `json:"forecast"`
	Id         int       `json:"id"`
	PerKwh     float32   `json:"perKwh"`
	SpotPerKwh float32   `json:"spotPerKwh"`
	StartTime  time.Time `json:"startTime"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// ChangeBatteryStatePayload defines model for ChangeBatteryStatePayload.
type ChangeBatteryStatePayload struct {
	Power *string                        `json:"power,omitempty"`
	State ChangeBatteryStatePayloadState `json:"state"`
}

// ChangeBatteryStatePayloadState defines model for ChangeBatteryStatePayload.State.
type ChangeBatteryStatePayloadState string

// ChangeFeedinPayload defines model for ChangeFeedinPayload.
type ChangeFeedinPayload struct {
	Disable bool `json:"disable"`
}

// ChangeInverterStatePayload defines model for ChangeInverterStatePayload.
type ChangeInverterStatePayload struct {
	State ChangeInverterStatePayloadState `json:"state"`
}

// ChangeInverterStatePayloadState defines model for ChangeInverterStatePayload.State.
type ChangeInverterStatePayloadState string

// Empty defines model for Empty.
type Empty = map[string]interface{}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`
}

// Property defines model for Property.
type Property struct {
	Id                *int       `json:"id,omitempty"`
	Identifier        *string    `json:"identifier,omitempty"`
	Slug              *string    `json:"slug,omitempty"`
	Timestamp         *time.Time `json:"timestamp,omitempty"`
	UnitOfMeasurement *string    `json:"unit_of_measurement,omitempty"`
	Value             *string    `json:"value,omitempty"`
}

// GetAmberPricesFromToParams defines parameters for GetAmberPricesFromTo.
type GetAmberPricesFromToParams struct {
	Site *string `form:"site,omitempty" json:"site,omitempty"`
}

// GetPropertyIdentifierSlugParams defines parameters for GetPropertyIdentifierSlug.
type GetPropertyIdentifierSlugParams struct {
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostBatteryStateJSONRequestBody defines body for PostBatteryState for application/json ContentType.
type PostBatteryStateJSONRequestBody = ChangeBatteryStatePayload

// PostInverterFeedinJSONRequestBody defines body for PostInverterFeedin for application/json ContentType.
type PostInverterFeedinJSONRequestBody = ChangeFeedinPayload

// PostInverterStateJSONRequestBody defines body for PostInverterState for application/json ContentType.
type PostInverterStateJSONRequestBody = ChangeInverterStatePayload

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /amber/prices/{from}/{to})
	GetAmberPricesFromTo(w http.ResponseWriter, r *http.Request, from time.Time, to time.Time, params GetAmberPricesFromToParams)
	// Login
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout and revoke refresh token
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Refresh access token using httpOnly cookie
	// (POST /auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)

	// (POST /battery/{state})
	PostBatteryState(w http.ResponseWriter, r *http.Request, state string)

	// (POST /inverter/feedin)
	PostInverterFeedin(w http.ResponseWriter, r *http.Request)

	// (POST /inverter/{state})
	PostInverterState(w http.ResponseWriter, r *http.Request, state string)
	// Get properties
	// (GET /properties)
	GetProperties(w http.ResponseWriter, r *http.Request)

	// (GET /property/{identifier}/{slug})
	GetPropertyIdentifierSlug(w http.ResponseWriter, r *http.Request, identifier string, slug string, params GetPropertyIdentifierSlugParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAmberPricesFromTo operation middleware
func (siw *ServerInterfaceWrapper) GetAmberPricesFromTo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "from" -------------
	var from time.Time

	err = runtime.BindStyledParameterWithOptions("simple", "from", r.PathValue("from"), &from, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Path parameter "to" -------------
	var to time.Time

	err = runtime.BindStyledParameterWithOptions("simple", "to", r.PathValue("to"), &to, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAmberPricesFromToParams

	// ------------- Optional query parameter "site" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "site", r.URL.Query(), &params.Site, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "site", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAmberPricesFromTo(w, r, from, to, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostBatteryState operation middleware
func (siw *ServerInterfaceWrapper) PostBatteryState(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "state" -------------
	var state string

	err = runtime.BindStyledParameterWithOptions("simple", "state", r.PathValue("state"), &state, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostBatteryState(w, r, state)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostInverterFeedin operation middleware
func (siw *ServerInterfaceWrapper) PostInverterFeedin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostInverterFeedin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostInverterState operation middleware
func (siw *ServerInterfaceWrapper) PostInverterState(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "state" -------------
	var state string

	err = runtime.BindStyledParameterWithOptions("simple", "state", r.PathValue("state"), &state, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostInverterState(w, r, state)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProperties operation middleware
func (siw *ServerInterfaceWrapper) GetProperties(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProperties(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPropertyIdentifierSlug operation middleware
func (siw *ServerInterfaceWrapper) GetPropertyIdentifierSlug(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier string

	err = runtime.BindStyledParameterWithOptions("simple", "identifier", r.PathValue("identifier"), &identifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPropertyIdentifierSlugParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPropertyIdentifierSlug(w, r, identifier, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/amber/prices/{from}/{to}", wrapper.GetAmberPricesFromTo)
	m.HandleFunc("POST "+options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	m.HandleFunc("POST "+options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	m.HandleFunc("POST "+options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	m.HandleFunc("POST "+options.BaseURL+"/battery/{state}", wrapper.PostBatteryState)
	m.HandleFunc("POST "+options.BaseURL+"/inverter/feedin", wrapper.PostInverterFeedin)
	m.HandleFunc("POST "+options.BaseURL+"/inverter/{state}", wrapper.PostInverterState)
	m.HandleFunc("GET "+options.BaseURL+"/properties", wrapper.GetProperties)
	m.HandleFunc("GET "+options.BaseURL+"/property/{identifier}/{slug}", wrapper.GetPropertyIdentifierSlug)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RX32/bNhD+Vwhuj04kp10f/JYOaxes2IIkQIEVRUBLJ4uNRDLHo1PB0P8+kJItyZYT",
	"G3O39i2xjvfju++OH1c80aXRChRZPltxm+RQivDnZTkHvEaZgP/PoDaAJCF8S3KhFBR3lQkfU7AJSkNS",
	"Kz7jUqUyEQSWyYxRDsx4J0xalgGkUjGNbAEKUBTnfMLhqyhNAXzG2x/5hFNwzC2hVAteT3iCIAjSS/Lh",
	"uhMX8cWrs2l8Fk/vphezOJ7F8d98wjONpSA+46kgOCNZwpjP1KFoUt6uYP2FScVKqRyB7Sf6y8aZVAQL",
	"QO8NVHrnA50uv0wjJMLSMQgLtj7V/qaRKU0DnAkdbMLNtS5AKB9PpoPkp2NVGsA/nvKBXXw+vXj1emOs",
	"nOeNt7VG0/Ux9iSQToyhM+mJeVNPOMKjkwgpn33yoPWY1GvaZDAkfQb3s+p4069/gN0G9M+bXPT8CyTk",
	"6/s1F2oBbwURYHVLguBaVIUW6e7MGv0EOIDhzfmbEcis9xLslCt9iRaK7D7RyrrStFUmucCFzzOVdvO3",
	"JW18kh3MIyel568RlL+IbJPH/qLfhWWyt9xUWjEvhlwaZ/5W3PXB/ZGv1BKQAJ/HewfHUL/OsiFGJ0Pl",
	"t9JQ5ePtfPmgF1LdwKODZpls8UJY+6RxOPzcOgNoIUGg0bmygEpsj6oo/G3xUgmbs5Mu9lhBbdrWaGVH",
	"7iCRJGDtPekHUL2y9wQdWI9Fu26cV7uBDtmLMgVFMpNbE8Zvf38T39zeX07HQLSFWwzN5yJ5cOY+85mD",
	"SqqxU34tWRKlOeWaVJLudXZfgrAOoQS1tTAfPuZj55aicFscmMbxiwzYP2LeUqpMh4ZKCh4/SgV0dstu",
	"AZeAfMKXgLa5CKfn8XnsE9EGlDCSz/ir8NMkTFNoXyT8BROF69BGqwx1WUcr0rX/uIBQqG932OBXKZ/x",
	"90Cd+LHvUJd3OnhEUQIBWj775K/kTLgiQNv+1c7xowP0nWvmg1tJYTsGZTVK1NVg/ttjPk/eh61ZXp2b",
	"E91mo8FJPxv6IM+fvYdmeEMfLuI4SEetqKWXMKbwOkZqFX2xjRDrgkiCMhz8GSHjM/5T1EnVqNWpUU+k",
	"1psUBKKoGi4NdRMCOVSWBUY0Asmee8N6wiPhKI8Kv3Oa29KOMONaW7p0lIfV1EIElt7qtDqqtudKGmzr",
	"ejg6vhH1v8T1gNjtyh1BMBgw68I2zVzhUX8dT3cl6pVaikKmLEEIq1EUNqwB68pSYLV2xQfQa0cHYe/t",
	"dlB4vZvEB71YQMq8+U5s7YgJlTKEpX4AhpAh2Jw1F0SXVfv7y2ndtIb/Z3f+hCfWXHTrOvZ056ZfLZNt",
	"rzQy+GoC04Zwrc37vpmzUi1YTmT+UkXFEq0fJDTIzRs9Gq2CWqmfB68vXne37Mhysq3l/v00uopOP6n7",
	"xfdIbxpjFszYxu4bsqXRgyOZJE0mAUaGPTr51slW20bNW/351q2FcCPF+bdEeaj29+Pr7fyz3QKRVAv7",
	"PUN80HgMHhs/4nyMvpZ+3AEZvg326cfrzuq/kEGbx8sBIqgroF9bf92/B2K9MvtlV9Gqe+rU0co/YeoD",
	"gKiuNqdu/avnEB733lTHkHlc0dom6vFuttR8K8uP1MJ7nAWZ/T3K6mP4tBbV1kAiM5n0qMPmFctkQYCN",
	"yq7rfwIAAP//QetIXXAWAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
