//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AmberUsageQuality.
const (
	Billable  AmberUsageQuality = "billable"
	Estimated AmberUsageQuality = "estimated"
)

// Valid indicates whether the value is a known member of the AmberUsageQuality enum.
func (e AmberUsageQuality) Valid() bool {
	switch e {
	case Billable:
		return true
	case Estimated:
		return true
	default:
		return false
	}
}

// Defines values for ChangeBatteryStatePayloadState.
const (
	Charge          ChangeBatteryStatePayloadState = "charge"
	Discharge       ChangeBatteryStatePayloadState = "discharge"
	SelfConsumption ChangeBatteryStatePayloadState = "self_consumption"
	Stop            ChangeBatteryStatePayloadState = "stop"
)

// Valid indicates whether the value is a known member of the ChangeBatteryStatePayloadState enum.
func (e ChangeBatteryStatePayloadState) Valid() bool {
	switch e {
	case Charge:
		return true
	case Discharge:
		return true
	case SelfConsumption:
		return true
	case Stop:
		return true
	default:
		return false
	}
}

// Defines values for ChangeInverterStatePayloadState.
const (
	Off ChangeInverterStatePayloadState = "off"
	On  ChangeInverterStatePayloadState = "on"
)

// Valid indicates whether the value is a known member of the ChangeInverterStatePayloadState enum.
func (e ChangeInverterStatePayloadState) Valid() bool {
	switch e {
	case Off:
		return true
	case On:
		return true
	default:
		return false
	}
}

// AmberPrice defines model for AmberPrice.
type AmberPrice struct {
	// ChannelType indicates if the price is feedin or general.
	ChannelType string    `json:"channelType"`
	CreatedAt   time.Time `json:"createdAt"`

	// Duration duration in minutes
	Duration int       `json:"duration"`
	EndTime  time.Time `json:"endTime"`

	// Forecast indicates if the price is a forecast price or not.
	Forecast   bool      `json:"forecast"`
	Id         int       `json:"id"`
	PerKwh     float32   `json:"perKwh"`
	SpotPerKwh float32   `json:"spotPerKwh"`
	StartTime  time.Time `json:"startTime"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// AmberUsage defines model for AmberUsage.
type AmberUsage struct {
	ChannelIdentifier string `json:"channelIdentifier"`
	ChannelType       string `json:"channelType"`

	// Cost total cost including GST
	Cost      float32   `json:"cost"`
	CreatedAt time.Time `json:"createdAt"`

	// Duration duration in minutes
	Duration int       `json:"duration"`
	EndTime  time.Time `json:"endTime"`
	Id       int       `json:"id"`

	// Kwh kWh consumed or generated (negative for generation)
	Kwh        float32           `json:"kwh"`
	PerKwh     float32           `json:"perKwh"`
	Quality    AmberUsageQuality `json:"quality"`
	SpotPerKwh float32           `json:"spotPerKwh"`
	StartTime  time.Time         `json:"startTime"`
	UpdatedAt  time.Time         `json:"updatedAt"`
}

// AmberUsageQuality defines model for AmberUsage.Quality.
type AmberUsageQuality string

// ChangeBatteryStatePayload defines model for ChangeBatteryStatePayload.
type ChangeBatteryStatePayload struct {
	Power *string                        `json:"power,omitempty"`
	State ChangeBatteryStatePayloadState `json:"state"`
}

// ChangeBatteryStatePayloadState defines model for ChangeBatteryStatePayload.State.
type ChangeBatteryStatePayloadState string

// ChangeFeedinPayload defines model for ChangeFeedinPayload.
type ChangeFeedinPayload struct {
	Disable bool `json:"disable"`
}

// ChangeInverterStatePayload defines model for ChangeInverterStatePayload.
type ChangeInverterStatePayload struct {
	State ChangeInverterStatePayloadState `json:"state"`
}

// ChangeInverterStatePayloadState defines model for ChangeInverterStatePayload.State.
type ChangeInverterStatePayloadState string

// Empty defines model for Empty.
type Empty = map[string]interface{}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`
}

// Property defines model for Property.
type Property struct {
	Id                *int       `json:"id,omitempty"`
	Identifier        *string    `json:"identifier,omitempty"`
	Slug              *string    `json:"slug,omitempty"`
	Timestamp         *time.Time `json:"timestamp,omitempty"`
	UnitOfMeasurement *string    `json:"unit_of_measurement,omitempty"`
	Value             *string    `json:"value,omitempty"`
}

// GetAmberPricesFromToParams defines parameters for GetAmberPricesFromTo.
type GetAmberPricesFromToParams struct {
	Site *string `form:"site,omitempty" json:"site,omitempty"`
}

// GetAmberUsageFromToParams defines parameters for GetAmberUsageFromTo.
type GetAmberUsageFromToParams struct {
	Site *string `form:"site,omitempty" json:"site,omitempty"`
}

// GetPropertyIdentifierSlugParams defines parameters for GetPropertyIdentifierSlug.
type GetPropertyIdentifierSlugParams struct {
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostBatteryStateJSONRequestBody defines body for PostBatteryState for application/json ContentType.
type PostBatteryStateJSONRequestBody = ChangeBatteryStatePayload

// PostInverterFeedinJSONRequestBody defines body for PostInverterFeedin for application/json ContentType.
type PostInverterFeedinJSONRequestBody = ChangeFeedinPayload

// PostInverterStateJSONRequestBody defines body for PostInverterState for application/json ContentType.
type PostInverterStateJSONRequestBody = ChangeInverterStatePayload

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /amber/prices/{from}/{to})
	GetAmberPricesFromTo(w http.ResponseWriter, r *http.Request, from time.Time, to time.Time, params GetAmberPricesFromToParams)

	// (GET /amber/usage/{from}/{to})
	GetAmberUsageFromTo(w http.ResponseWriter, r *http.Request, from time.Time, to time.Time, params GetAmberUsageFromToParams)
	// Login
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout and revoke refresh token
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Refresh access token using httpOnly cookie
	// (POST /auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)

	// (POST /battery/{state})
	PostBatteryState(w http.ResponseWriter, r *http.Request, state string)

	// (POST /inverter/feedin)
	PostInverterFeedin(w http.ResponseWriter, r *http.Request)

	// (POST /inverter/{state})
	PostInverterState(w http.ResponseWriter, r *http.Request, state string)
	// Get properties
	// (GET /properties)
	GetProperties(w http.ResponseWriter, r *http.Request)

	// (GET /property/{identifier}/{slug})
	GetPropertyIdentifierSlug(w http.ResponseWriter, r *http.Request, identifier string, slug string, params GetPropertyIdentifierSlugParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAmberPricesFromTo operation middleware
func (siw *ServerInterfaceWrapper) GetAmberPricesFromTo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "from" -------------
	var from time.Time

	err = runtime.BindStyledParameterWithOptions("simple", "from", r.PathValue("from"), &from, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Path parameter "to" -------------
	var to time.Time

	err = runtime.BindStyledParameterWithOptions("simple", "to", r.PathValue("to"), &to, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAmberPricesFromToParams

	// ------------- Optional query parameter "site" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "site", r.URL.Query(), &params.Site, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "site", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAmberPricesFromTo(w, r, from, to, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAmberUsageFromTo operation middleware
func (siw *ServerInterfaceWrapper) GetAmberUsageFromTo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "from" -------------
	var from time.Time

	err = runtime.BindStyledParameterWithOptions("simple", "from", r.PathValue("from"), &from, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Path parameter "to" -------------
	var to time.Time

	err = runtime.BindStyledParameterWithOptions("simple", "to", r.PathValue("to"), &to, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAmberUsageFromToParams

	// ------------- Optional query parameter "site" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "site", r.URL.Query(), &params.Site, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "site", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAmberUsageFromTo(w, r, from, to, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostBatteryState operation middleware
func (siw *ServerInterfaceWrapper) PostBatteryState(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "state" -------------
	var state string

	err = runtime.BindStyledParameterWithOptions("simple", "state", r.PathValue("state"), &state, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostBatteryState(w, r, state)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostInverterFeedin operation middleware
func (siw *ServerInterfaceWrapper) PostInverterFeedin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostInverterFeedin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostInverterState operation middleware
func (siw *ServerInterfaceWrapper) PostInverterState(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "state" -------------
	var state string

	err = runtime.BindStyledParameterWithOptions("simple", "state", r.PathValue("state"), &state, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostInverterState(w, r, state)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProperties operation middleware
func (siw *ServerInterfaceWrapper) GetProperties(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProperties(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPropertyIdentifierSlug operation middleware
func (siw *ServerInterfaceWrapper) GetPropertyIdentifierSlug(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "identifier" -------------
	var identifier string

	err = runtime.BindStyledParameterWithOptions("simple", "identifier", r.PathValue("identifier"), &identifier, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identifier", Err: err})
		return
	}

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPropertyIdentifierSlugParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPropertyIdentifierSlug(w, r, identifier, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/amber/prices/{from}/{to}", wrapper.GetAmberPricesFromTo)
	m.HandleFunc("GET "+options.BaseURL+"/amber/usage/{from}/{to}", wrapper.GetAmberUsageFromTo)
	m.HandleFunc("POST "+options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	m.HandleFunc("POST "+options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	m.HandleFunc("POST "+options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	m.HandleFunc("POST "+options.BaseURL+"/battery/{state}", wrapper.PostBatteryState)
	m.HandleFunc("POST "+options.BaseURL+"/inverter/feedin", wrapper.PostInverterFeedin)
	m.HandleFunc("POST "+options.BaseURL+"/inverter/{state}", wrapper.PostInverterState)
	m.HandleFunc("GET "+options.BaseURL+"/properties", wrapper.GetProperties)
	m.HandleFunc("GET "+options.BaseURL+"/property/{identifier}/{slug}", wrapper.GetPropertyIdentifierSlug)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYX2/bNhD/KgS3hw1wbDnp+uC3dGi7YMUWxBkKrCgCWjrJrCWSIY9ODUPffSApW5It",
	"JTbmtim2t0Q63Z/f/e6f1zSWhZICBBo6WVMTz6Fg/s/LYgb6WvMY3H9KSwUaOfh38ZwJAfntSvmXCZhY",
	"c4VcCjqhXCQ8ZgiG8JTgHIhySgg3JAVIuCBSkwwEaJYP6YDCZ1aoHOiEVg/pgKJXTA1qLjJaDmisgSEk",
	"l+jM1V+cR+cXZ+PoLBrfjs8nUTSJor/pgKZSFwzphCYM4Qx5AV06E6tZcHk3gs0bwgUpuLAIpunoL1tl",
	"XCBkoJ02EMmtM3Q6/1KpIWYGj0GYkc1X1TOpiZDYwhm1ha25mZQ5MOHs8aTl/LgrSgX694d5Sy4ajs8v",
	"XmyFhXW8cbJGSbw+Rh6ZxhNjaFVyYt6UA6rh3nINCZ18cKA1mNRI2qBVJE0GN72qedOMv4XdFvSPW1/k",
	"7BPE6OLzRfqXYVl/kV4lIJCnHHQbg9fjzkJrV/ZhxSm7SIoSWU7cO8JFnNuEi4y8nd42qRgNLzqI8KyK",
	"/SL6OtV+SPUtQim1/V+8n5NYCmMLSOrWipCQnwRkDPkSXFPYPOdS/NyMbzzsrsZjKv3espzjygsLW7i6",
	"mPE8Z7PchQoGeeEccgyu0WpI7IHxn2wdO/1ir3pD/mu0q8L7Uq3l1zkTGbxiiKBXU2QI12yVS5bsdxol",
	"H3a6y8vhy660Oi1NlhjI07tAXlWjoDPnZ8LN9m+DUrXZ0/Eld9WgGM6fRD740R/0G7+n9IabcOOJ2wy4",
	"e6ju2N182G/5SixBI+jH8d7D0ccv07SN0clQeV2oUN17b97JjIsbuLcQRsAOL5gxD1K3Oxs1VoE2EGvA",
	"zrozoAXbLWWWu0X0qRC23w5q210BVW4bJYXpmJwsjsGYO5QLEI2we4y2pLusXQflq31DhzR93jO/p7+9",
	"jG6md5edY9zkNmuLz1i8sOoudZ6DiFddX7m2ZZAV6pRtVHC8k+ldAcxYDQWInYa6eD/v+m7JcrvDgXEU",
	"PcmA/hJzklyk0ieUo9f4ngvAsymZgl76DrsEbcJYHQ+jYeQckQoEU5xO6IV/NPDV5NM3Ym4AjfymbUbr",
	"VMuiHK1Rlu5lBj5Ql27f4a8SOqFvAeu7yrzRsriVXqNmBSBoQycf3IBPmc09tNVfVR3fW9Auc6E+qOHo",
	"u6M/2jqJum7Vf/WZ85M2YQvNq1ZzomnXaRzlo6YP0vzRaQjF6/NwHkV+4ZUCK3oxpXJ3InEpRp9MWPtq",
	"Ixyh8B/+qCGlE/rDqL6CR9UJPGrcv+XWBaY1WwUutbcwDWi1MMQzItxeZugEy8GGJtat6UexxC/2fST5",
	"nxDfghDh1jqaED73JGHIalJYnI9yN4jCCmU6iHAtDV5anPt5VcEEBl/JZHVUfI+F1RrhZbufumSU/xLb",
	"A2xXc7gDRS9AjPUjNrW5Q/5FNN6/gq7EkuU8IbEGPy9ZbvxsMLYomF5tVNEW9NLiQdg7uT0UXuw78U5m",
	"mTvCLO7blhYJEwnRsJQLIBpSDWZOwtZQe1U9f9qtm0rwW2bnD3ggYfvZxNGTnZtmtIRXuZKawGflmdaG",
	"ayPe1E2s4SIjc0T1p8hXJJZywSEgNwtHymjtV9jycfCaF01PV203KFNJ9veoznZ0+krtv8g6chOEiRcj",
	"W7kvyJZwJHR4EgdPPIxEN+jkUserg2cUfht+PHWb6yjcZ/RLotw+AfvxdXLEtShA5CIzzxnig8qjdYF+",
	"j/XReUJ/vwXSPhj71sXrWuprrELbi/aARagOoBlbs92/BSSNMJthr0br+v4tR2t315YHALGqfzebulP4",
	"EB7z5k9th5O5e6s1werxanY2+mo1P3If7lHmV+3nuFofw6fNYm0UxDzlcYM6ZLYiKc8RdNiyy/KfAAAA",
	"//8PH7Kr4BwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
