// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iter"
	"time"

	"github.com/anicoll/winet-integration/internal/pkg/database/db"
	mock "github.com/stretchr/testify/mock"
)

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// GetAmberPrices provides a mock function for the type Database
func (_mock *Database) GetAmberPrices(ctx context.Context, from time.Time, to time.Time, site *string) ([]db.Amberprice, error) {
	ret := _mock.Called(ctx, from, to, site)

	if len(ret) == 0 {
		panic("no return value specified for GetAmberPrices")
	}

	var r0 []db.Amberprice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *string) ([]db.Amberprice, error)); ok {
		return returnFunc(ctx, from, to, site)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *string) []db.Amberprice); ok {
		r0 = returnFunc(ctx, from, to, site)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Amberprice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, *string) error); ok {
		r1 = returnFunc(ctx, from, to, site)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetAmberPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAmberPrices'
type Database_GetAmberPrices_Call struct {
	*mock.Call
}

// GetAmberPrices is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - site *string
func (_e *Database_Expecter) GetAmberPrices(ctx interface{}, from interface{}, to interface{}, site interface{}) *Database_GetAmberPrices_Call {
	return &Database_GetAmberPrices_Call{Call: _e.mock.On("GetAmberPrices", ctx, from, to, site)}
}

func (_c *Database_GetAmberPrices_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, site *string)) *Database_GetAmberPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Database_GetAmberPrices_Call) Return(amberprices []db.Amberprice, err error) *Database_GetAmberPrices_Call {
	_c.Call.Return(amberprices, err)
	return _c
}

func (_c *Database_GetAmberPrices_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time, site *string) ([]db.Amberprice, error)) *Database_GetAmberPrices_Call {
	_c.Call.Return(run)
	return _c
}

// GetAmberUsage provides a mock function for the type Database
func (_mock *Database) GetAmberUsage(ctx context.Context, from time.Time, to time.Time) ([]db.Amberusage, error) {
	ret := _mock.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetAmberUsage")
	}

	var r0 []db.Amberusage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]db.Amberusage, error)); ok {
		return returnFunc(ctx, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []db.Amberusage); ok {
		r0 = returnFunc(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Amberusage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetAmberUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAmberUsage'
type Database_GetAmberUsage_Call struct {
	*mock.Call
}

// GetAmberUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *Database_Expecter) GetAmberUsage(ctx interface{}, from interface{}, to interface{}) *Database_GetAmberUsage_Call {
	return &Database_GetAmberUsage_Call{Call: _e.mock.On("GetAmberUsage", ctx, from, to)}
}

func (_c *Database_GetAmberUsage_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *Database_GetAmberUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_GetAmberUsage_Call) Return(amberusages []db.Amberusage, err error) *Database_GetAmberUsage_Call {
	_c.Call.Return(amberusages, err)
	return _c
}

func (_c *Database_GetAmberUsage_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time) ([]db.Amberusage, error)) *Database_GetAmberUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestProperties provides a mock function for the type Database
func (_mock *Database) GetLatestProperties(ctx context.Context) (iter.Seq[db.Property], error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestProperties")
	}

	var r0 iter.Seq[db.Property]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (iter.Seq[db.Property], error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) iter.Seq[db.Property]); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[db.Property])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetLatestProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestProperties'
type Database_GetLatestProperties_Call struct {
	*mock.Call
}

// GetLatestProperties is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Database_Expecter) GetLatestProperties(ctx interface{}) *Database_GetLatestProperties_Call {
	return &Database_GetLatestProperties_Call{Call: _e.mock.On("GetLatestProperties", ctx)}
}

func (_c *Database_GetLatestProperties_Call) Run(run func(ctx context.Context)) *Database_GetLatestProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Database_GetLatestProperties_Call) Return(seq iter.Seq[db.Property], err error) *Database_GetLatestProperties_Call {
	_c.Call.Return(seq, err)
	return _c
}

func (_c *Database_GetLatestProperties_Call) RunAndReturn(run func(ctx context.Context) (iter.Seq[db.Property], error)) *Database_GetLatestProperties_Call {
	_c.Call.Return(run)
	return _c
}

// GetProperties provides a mock function for the type Database
func (_mock *Database) GetProperties(ctx context.Context, identifier string, slug string, from *time.Time, to *time.Time) ([]db.Property, error) {
	ret := _mock.Called(ctx, identifier, slug, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetProperties")
	}

	var r0 []db.Property
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *time.Time, *time.Time) ([]db.Property, error)); ok {
		return returnFunc(ctx, identifier, slug, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *time.Time, *time.Time) []db.Property); ok {
		r0 = returnFunc(ctx, identifier, slug, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Property)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(ctx, identifier, slug, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProperties'
type Database_GetProperties_Call struct {
	*mock.Call
}

// GetProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - slug string
//   - from *time.Time
//   - to *time.Time
func (_e *Database_Expecter) GetProperties(ctx interface{}, identifier interface{}, slug interface{}, from interface{}, to interface{}) *Database_GetProperties_Call {
	return &Database_GetProperties_Call{Call: _e.mock.On("GetProperties", ctx, identifier, slug, from, to)}
}

func (_c *Database_GetProperties_Call) Run(run func(ctx context.Context, identifier string, slug string, from *time.Time, to *time.Time)) *Database_GetProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Database_GetProperties_Call) Return(propertys []db.Property, err error) *Database_GetProperties_Call {
	_c.Call.Return(propertys, err)
	return _c
}

func (_c *Database_GetProperties_Call) RunAndReturn(run func(ctx context.Context, identifier string, slug string, from *time.Time, to *time.Time) ([]db.Property, error)) *Database_GetProperties_Call {
	_c.Call.Return(run)
	return _c
}
