// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWinetService creates a new instance of WinetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWinetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WinetService {
	mock := &WinetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WinetService is an autogenerated mock type for the WinetService type
type WinetService struct {
	mock.Mock
}

type WinetService_Expecter struct {
	mock *mock.Mock
}

func (_m *WinetService) EXPECT() *WinetService_Expecter {
	return &WinetService_Expecter{mock: &_m.Mock}
}

// SendBatteryStopCommand provides a mock function for the type WinetService
func (_mock *WinetService) SendBatteryStopCommand() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendBatteryStopCommand")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WinetService_SendBatteryStopCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatteryStopCommand'
type WinetService_SendBatteryStopCommand_Call struct {
	*mock.Call
}

// SendBatteryStopCommand is a helper method to define mock.On call
func (_e *WinetService_Expecter) SendBatteryStopCommand() *WinetService_SendBatteryStopCommand_Call {
	return &WinetService_SendBatteryStopCommand_Call{Call: _e.mock.On("SendBatteryStopCommand")}
}

func (_c *WinetService_SendBatteryStopCommand_Call) Run(run func()) *WinetService_SendBatteryStopCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WinetService_SendBatteryStopCommand_Call) Return(b bool, err error) *WinetService_SendBatteryStopCommand_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WinetService_SendBatteryStopCommand_Call) RunAndReturn(run func() (bool, error)) *WinetService_SendBatteryStopCommand_Call {
	_c.Call.Return(run)
	return _c
}

// SendChargeCommand provides a mock function for the type WinetService
func (_mock *WinetService) SendChargeCommand(chargePower string) (bool, error) {
	ret := _mock.Called(chargePower)

	if len(ret) == 0 {
		panic("no return value specified for SendChargeCommand")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(chargePower)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(chargePower)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(chargePower)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WinetService_SendChargeCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendChargeCommand'
type WinetService_SendChargeCommand_Call struct {
	*mock.Call
}

// SendChargeCommand is a helper method to define mock.On call
//   - chargePower string
func (_e *WinetService_Expecter) SendChargeCommand(chargePower interface{}) *WinetService_SendChargeCommand_Call {
	return &WinetService_SendChargeCommand_Call{Call: _e.mock.On("SendChargeCommand", chargePower)}
}

func (_c *WinetService_SendChargeCommand_Call) Run(run func(chargePower string)) *WinetService_SendChargeCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WinetService_SendChargeCommand_Call) Return(b bool, err error) *WinetService_SendChargeCommand_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WinetService_SendChargeCommand_Call) RunAndReturn(run func(chargePower string) (bool, error)) *WinetService_SendChargeCommand_Call {
	_c.Call.Return(run)
	return _c
}

// SendDischargeCommand provides a mock function for the type WinetService
func (_mock *WinetService) SendDischargeCommand(dischargePower string) (bool, error) {
	ret := _mock.Called(dischargePower)

	if len(ret) == 0 {
		panic("no return value specified for SendDischargeCommand")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(dischargePower)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(dischargePower)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dischargePower)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WinetService_SendDischargeCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDischargeCommand'
type WinetService_SendDischargeCommand_Call struct {
	*mock.Call
}

// SendDischargeCommand is a helper method to define mock.On call
//   - dischargePower string
func (_e *WinetService_Expecter) SendDischargeCommand(dischargePower interface{}) *WinetService_SendDischargeCommand_Call {
	return &WinetService_SendDischargeCommand_Call{Call: _e.mock.On("SendDischargeCommand", dischargePower)}
}

func (_c *WinetService_SendDischargeCommand_Call) Run(run func(dischargePower string)) *WinetService_SendDischargeCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WinetService_SendDischargeCommand_Call) Return(b bool, err error) *WinetService_SendDischargeCommand_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WinetService_SendDischargeCommand_Call) RunAndReturn(run func(dischargePower string) (bool, error)) *WinetService_SendDischargeCommand_Call {
	_c.Call.Return(run)
	return _c
}

// SendInverterStateChangeCommand provides a mock function for the type WinetService
func (_mock *WinetService) SendInverterStateChangeCommand(disable bool) (bool, error) {
	ret := _mock.Called(disable)

	if len(ret) == 0 {
		panic("no return value specified for SendInverterStateChangeCommand")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) (bool, error)); ok {
		return returnFunc(disable)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) bool); ok {
		r0 = returnFunc(disable)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(disable)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WinetService_SendInverterStateChangeCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInverterStateChangeCommand'
type WinetService_SendInverterStateChangeCommand_Call struct {
	*mock.Call
}

// SendInverterStateChangeCommand is a helper method to define mock.On call
//   - disable bool
func (_e *WinetService_Expecter) SendInverterStateChangeCommand(disable interface{}) *WinetService_SendInverterStateChangeCommand_Call {
	return &WinetService_SendInverterStateChangeCommand_Call{Call: _e.mock.On("SendInverterStateChangeCommand", disable)}
}

func (_c *WinetService_SendInverterStateChangeCommand_Call) Run(run func(disable bool)) *WinetService_SendInverterStateChangeCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WinetService_SendInverterStateChangeCommand_Call) Return(b bool, err error) *WinetService_SendInverterStateChangeCommand_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WinetService_SendInverterStateChangeCommand_Call) RunAndReturn(run func(disable bool) (bool, error)) *WinetService_SendInverterStateChangeCommand_Call {
	_c.Call.Return(run)
	return _c
}

// SendSelfConsumptionCommand provides a mock function for the type WinetService
func (_mock *WinetService) SendSelfConsumptionCommand() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendSelfConsumptionCommand")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WinetService_SendSelfConsumptionCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSelfConsumptionCommand'
type WinetService_SendSelfConsumptionCommand_Call struct {
	*mock.Call
}

// SendSelfConsumptionCommand is a helper method to define mock.On call
func (_e *WinetService_Expecter) SendSelfConsumptionCommand() *WinetService_SendSelfConsumptionCommand_Call {
	return &WinetService_SendSelfConsumptionCommand_Call{Call: _e.mock.On("SendSelfConsumptionCommand")}
}

func (_c *WinetService_SendSelfConsumptionCommand_Call) Run(run func()) *WinetService_SendSelfConsumptionCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WinetService_SendSelfConsumptionCommand_Call) Return(b bool, err error) *WinetService_SendSelfConsumptionCommand_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WinetService_SendSelfConsumptionCommand_Call) RunAndReturn(run func() (bool, error)) *WinetService_SendSelfConsumptionCommand_Call {
	_c.Call.Return(run)
	return _c
}

// SetFeedInLimitation provides a mock function for the type WinetService
func (_mock *WinetService) SetFeedInLimitation(feedinLimited bool) (bool, error) {
	ret := _mock.Called(feedinLimited)

	if len(ret) == 0 {
		panic("no return value specified for SetFeedInLimitation")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) (bool, error)); ok {
		return returnFunc(feedinLimited)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) bool); ok {
		r0 = returnFunc(feedinLimited)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(feedinLimited)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WinetService_SetFeedInLimitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFeedInLimitation'
type WinetService_SetFeedInLimitation_Call struct {
	*mock.Call
}

// SetFeedInLimitation is a helper method to define mock.On call
//   - feedinLimited bool
func (_e *WinetService_Expecter) SetFeedInLimitation(feedinLimited interface{}) *WinetService_SetFeedInLimitation_Call {
	return &WinetService_SetFeedInLimitation_Call{Call: _e.mock.On("SetFeedInLimitation", feedinLimited)}
}

func (_c *WinetService_SetFeedInLimitation_Call) Run(run func(feedinLimited bool)) *WinetService_SetFeedInLimitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WinetService_SetFeedInLimitation_Call) Return(b bool, err error) *WinetService_SetFeedInLimitation_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WinetService_SetFeedInLimitation_Call) RunAndReturn(run func(feedinLimited bool) (bool, error)) *WinetService_SetFeedInLimitation_Call {
	_c.Call.Return(run)
	return _c
}
