CREATE TABLE Device (
    id            NVARCHAR(255)  NOT NULL PRIMARY KEY,
    model         NVARCHAR(MAX)  NULL,
    serial_number NVARCHAR(MAX)  NULL,
    created_at    DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
