// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iter"
	"time"

	"github.com/anicoll/winet-integration/internal/pkg/store"
	mock "github.com/stretchr/testify/mock"
)

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// GetAmberPrices provides a mock function for the type Database
func (_mock *Database) GetAmberPrices(ctx context.Context, from time.Time, to time.Time, site *string) ([]store.Amberprice, error) {
	ret := _mock.Called(ctx, from, to, site)

	if len(ret) == 0 {
		panic("no return value specified for GetAmberPrices")
	}

	var r0 []store.Amberprice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *string) ([]store.Amberprice, error)); ok {
		return returnFunc(ctx, from, to, site)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *string) []store.Amberprice); ok {
		r0 = returnFunc(ctx, from, to, site)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Amberprice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, *string) error); ok {
		r1 = returnFunc(ctx, from, to, site)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetAmberPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAmberPrices'
type Database_GetAmberPrices_Call struct {
	*mock.Call
}

// GetAmberPrices is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - site *string
func (_e *Database_Expecter) GetAmberPrices(ctx interface{}, from interface{}, to interface{}, site interface{}) *Database_GetAmberPrices_Call {
	return &Database_GetAmberPrices_Call{Call: _e.mock.On("GetAmberPrices", ctx, from, to, site)}
}

func (_c *Database_GetAmberPrices_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, site *string)) *Database_GetAmberPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Database_GetAmberPrices_Call) Return(amberprices []store.Amberprice, err error) *Database_GetAmberPrices_Call {
	_c.Call.Return(amberprices, err)
	return _c
}

func (_c *Database_GetAmberPrices_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time, site *string) ([]store.Amberprice, error)) *Database_GetAmberPrices_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestProperties provides a mock function for the type Database
func (_mock *Database) GetLatestProperties(ctx context.Context) (iter.Seq[store.Property], error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestProperties")
	}

	var r0 iter.Seq[store.Property]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (iter.Seq[store.Property], error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) iter.Seq[store.Property]); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[store.Property])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetLatestProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestProperties'
type Database_GetLatestProperties_Call struct {
	*mock.Call
}

// GetLatestProperties is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Database_Expecter) GetLatestProperties(ctx interface{}) *Database_GetLatestProperties_Call {
	return &Database_GetLatestProperties_Call{Call: _e.mock.On("GetLatestProperties", ctx)}
}

func (_c *Database_GetLatestProperties_Call) Run(run func(ctx context.Context)) *Database_GetLatestProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Database_GetLatestProperties_Call) Return(seq iter.Seq[store.Property], err error) *Database_GetLatestProperties_Call {
	_c.Call.Return(seq, err)
	return _c
}

func (_c *Database_GetLatestProperties_Call) RunAndReturn(run func(ctx context.Context) (iter.Seq[store.Property], error)) *Database_GetLatestProperties_Call {
	_c.Call.Return(run)
	return _c
}
