// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anicoll/winet-integration/pkg/sockets"
	mock "github.com/stretchr/testify/mock"
)

// NewConnection creates a new instance of Connection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connection {
	mock := &Connection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Connection is an autogenerated mock type for the Connection type
type Connection struct {
	mock.Mock
}

type Connection_Expecter struct {
	mock *mock.Mock
}

func (_m *Connection) EXPECT() *Connection_Expecter {
	return &Connection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Connection
func (_mock *Connection) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Connection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Connection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Connection_Expecter) Close() *Connection_Close_Call {
	return &Connection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Connection_Close_Call) Run(run func()) *Connection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Close_Call) Return(err error) *Connection_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Connection_Close_Call) RunAndReturn(run func() error) *Connection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Dial provides a mock function for the type Connection
func (_mock *Connection) Dial(ctx context.Context, url string, subprotocol string) error {
	ret := _mock.Called(ctx, url, subprotocol)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, url, subprotocol)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Connection_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type Connection_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - subprotocol string
func (_e *Connection_Expecter) Dial(ctx interface{}, url interface{}, subprotocol interface{}) *Connection_Dial_Call {
	return &Connection_Dial_Call{Call: _e.mock.On("Dial", ctx, url, subprotocol)}
}

func (_c *Connection_Dial_Call) Run(run func(ctx context.Context, url string, subprotocol string)) *Connection_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Connection_Dial_Call) Return(err error) *Connection_Dial_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Connection_Dial_Call) RunAndReturn(run func(ctx context.Context, url string, subprotocol string) error) *Connection_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function for the type Connection
func (_mock *Connection) IsConnected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Connection_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type Connection_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *Connection_Expecter) IsConnected() *Connection_IsConnected_Call {
	return &Connection_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *Connection_IsConnected_Call) Run(run func()) *Connection_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_IsConnected_Call) Return(b bool) *Connection_IsConnected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Connection_IsConnected_Call) RunAndReturn(run func() bool) *Connection_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type Connection
func (_mock *Connection) Send(msg sockets.Msg) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(sockets.Msg) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Connection_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Connection_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - msg sockets.Msg
func (_e *Connection_Expecter) Send(msg interface{}) *Connection_Send_Call {
	return &Connection_Send_Call{Call: _e.mock.On("Send", msg)}
}

func (_c *Connection_Send_Call) Run(run func(msg sockets.Msg)) *Connection_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sockets.Msg
		if args[0] != nil {
			arg0 = args[0].(sockets.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Connection_Send_Call) Return(err error) *Connection_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Connection_Send_Call) RunAndReturn(run func(msg sockets.Msg) error) *Connection_Send_Call {
	_c.Call.Return(run)
	return _c
}
