CREATE TABLE IF NOT EXISTS Inverter (
    id 				TEXT PRIMARY KEY,
    state        	TEXT NOT NULL, -- e.g. "ON", "OFF", "FAULT"
    battery_state   TEXT NOT NULL, -- e.g. "CHARGING", "DISCHARGING", "STOPPED", "SELF_CONSUMPTION"
    charge_rate 	NUMERIC(3, 1) NOT NULL,
    feedin_enabled  BOOL NOT NULL DEFAULT FALSE,
    created_at 		TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at 		TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);