// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anicoll/winet-integration/internal/pkg/database/db"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenStore creates a new instance of TokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenStore {
	mock := &TokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenStore is an autogenerated mock type for the TokenStore type
type TokenStore struct {
	mock.Mock
}

type TokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenStore) EXPECT() *TokenStore_Expecter {
	return &TokenStore_Expecter{mock: &_m.Mock}
}

// DeleteExpiredRefreshTokens provides a mock function for the type TokenStore
func (_mock *TokenStore) DeleteExpiredRefreshTokens(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredRefreshTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenStore_DeleteExpiredRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredRefreshTokens'
type TokenStore_DeleteExpiredRefreshTokens_Call struct {
	*mock.Call
}

// DeleteExpiredRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TokenStore_Expecter) DeleteExpiredRefreshTokens(ctx interface{}) *TokenStore_DeleteExpiredRefreshTokens_Call {
	return &TokenStore_DeleteExpiredRefreshTokens_Call{Call: _e.mock.On("DeleteExpiredRefreshTokens", ctx)}
}

func (_c *TokenStore_DeleteExpiredRefreshTokens_Call) Run(run func(ctx context.Context)) *TokenStore_DeleteExpiredRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenStore_DeleteExpiredRefreshTokens_Call) Return(err error) *TokenStore_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenStore_DeleteExpiredRefreshTokens_Call) RunAndReturn(run func(ctx context.Context) error) *TokenStore_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type TokenStore
func (_mock *TokenStore) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenStore_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type TokenStore_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *TokenStore_Expecter) DeleteRefreshToken(ctx interface{}, tokenHash interface{}) *TokenStore_DeleteRefreshToken_Call {
	return &TokenStore_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, tokenHash)}
}

func (_c *TokenStore_DeleteRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *TokenStore_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenStore_DeleteRefreshToken_Call) Return(err error) *TokenStore_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenStore_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *TokenStore_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function for the type TokenStore
func (_mock *TokenStore) GetRefreshToken(ctx context.Context, tokenHash string) (db.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 db.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(db.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenStore_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type TokenStore_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *TokenStore_Expecter) GetRefreshToken(ctx interface{}, tokenHash interface{}) *TokenStore_GetRefreshToken_Call {
	return &TokenStore_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, tokenHash)}
}

func (_c *TokenStore_GetRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *TokenStore_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenStore_GetRefreshToken_Call) Return(refreshToken db.RefreshToken, err error) *TokenStore_GetRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *TokenStore_GetRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (db.RefreshToken, error)) *TokenStore_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function for the type TokenStore
func (_mock *TokenStore) StoreRefreshToken(ctx context.Context, arg db.StoreRefreshTokenParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.StoreRefreshTokenParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenStore_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type TokenStore_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.StoreRefreshTokenParams
func (_e *TokenStore_Expecter) StoreRefreshToken(ctx interface{}, arg interface{}) *TokenStore_StoreRefreshToken_Call {
	return &TokenStore_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, arg)}
}

func (_c *TokenStore_StoreRefreshToken_Call) Run(run func(ctx context.Context, arg db.StoreRefreshTokenParams)) *TokenStore_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.StoreRefreshTokenParams
		if args[1] != nil {
			arg1 = args[1].(db.StoreRefreshTokenParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenStore_StoreRefreshToken_Call) Return(err error) *TokenStore_StoreRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenStore_StoreRefreshToken_Call) RunAndReturn(run func(ctx context.Context, arg db.StoreRefreshTokenParams) error) *TokenStore_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
