openapi: "3.0.0"
info:
  version: 1.0.0
  title: Winet-S Server
paths:
  /properties:
    get:
      summary: Get properties
      responses:
        "200":
          description: properties response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Property"
  /amber/prices/{from}/{to}:
    get:
      parameters:
        - name: site
          in: query
          required: false
          default: "default"
          schema:
            type: string
        - name: from
          in: path
          required: true
          schema:
            type: string
            format: date-time
            example: "2023-10-01T12:00:00Z"
        - name: to
          in: path
          required: true
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: returns amber prices.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AmberPrice"
  /property/{identifier}/{slug}:
    get:
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
        - name: slug
          in: path
          required: true
          schema:
            type: string
        - name: from
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: returns specific properties by filter.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Property"

  /battery/{state}:
    post:
      parameters:
        - name: state
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Change State Payload
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeBatteryStatePayload"
      responses:
        "200":
          description: change state response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /inverter/{state}:
    post:
      parameters:
        - name: state
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Change State Payload
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeInverterStatePayload"
      responses:
        "200":
          description: change state response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /inverter/feedin:
    post:
      requestBody:
        description: Change Feed in settings
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeFeedinPayload"
      responses:
        "200":
          description: change state response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      type: object
    ChangeBatteryStatePayload:
      type: object
      required:
        - state
      properties:
        power:
          type: string
          example: 6.6
        state:
          type: string
          in: path
          example: self_consumption
          enum:
            - self_consumption
            - charge
            - discharge
            - stop
    ChangeInverterStatePayload:
      type: object
      required:
        - state
      properties:
        state:
          type: string
          in: path
          example: "on"
          enum:
            - "on"
            - "off"
    ChangeFeedinPayload:
      type: object
      required:
        - disable
      properties:
        disable:
          type: boolean
          example: true
    AmberPrice:
      type: object
      required:
        - id
        - duration
        - forecast
        - channelType
        - createdAt
        - updatedAt
        - endTime
        - startTime
        - spotPerKwh
        - perKwh
      properties:
        id:
          type: integer
          example: 1
        duration:
          type: integer
          example: 5
          description: duration in minutes
        forecast:
          type: boolean
          example: true
          description: indicates if the price is a forecast price or not.
        channelType:
          type: string
          example: "general"
          description: indicates if the price is feedin or general.
        createdAt:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        endTime:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        startTime:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        perKwh:
          type: number
          example: 0.1234
        spotPerKwh:
          type: number
          example: 0.1234

    Property:
      type: object
      required:
        - disable
      properties:
        id:
          type: integer
          example: 1
        timestamp:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        unit_of_measurement:
          type: string
          example: "kWh"
        value:
          type: string
          example: "100"
        identifier:
          type: string
          example: "SH60RS_A1"
        slug:
          type: string
          example: "backup_frequency"
