name: Go Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Build
        run: make build

      - name: Test
        run: make test
